"""Shared public size limits for bounded Dolphin lifecycle reads."""

REPO_LIST_PAGE_SIZE = 25
REPO_LIST_CURSOR_MAX_LENGTH = 8_192
ENTITY_ID_MAX_LENGTH = 64
OPERATION_ID_MAX_LENGTH = 128
HEAD_COMMIT_MAX_LENGTH = 64
ISO_TIMESTAMP_MAX_LENGTH = 64
