name: Publish VS Code Extension

on:
  release:
    types: [published] # Trigger on new GitHub releases

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-extension
    steps:
      - uses: actions/checkout@v4

      # (Optional) Build your extension if needed, generating the .vsix file
      - name: Install dependencies
        run: npm install
      - name: Package extension
        run: vsce package # Assuming you have vsce installed and configured

      - name: Publish to VS Code Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_TOKEN }} # Your VS Code Marketplace PAT as a secret
          publisher: plasticbeach
          extensionFile: dolphin.vsix

      # - name: Publish to Open VSX Registry
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }} # Your Open VSX access token as a secret
      #     publisher: your-publisher-id
      #     target: open-vsx
      #     extensionFile: your-extension-name.vsix
