name: Publish VS Code Extension

on:
  release:
    types: [published] # Trigger on new GitHub releases

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install extension dependencies
        working-directory: ./vscode-extension
        run: npm install

      - name: Install webview dependencies
        working-directory: ./vscode-extension/webview
        run: bun install
      
      - name: Build webview
        working-directory: ./vscode-extension/webview
        run: bun run build
      
      - name: Publish extension
        working-directory: ./vscode-extension
        run: npx vsce publish --pat ${{ secrets.VSCE_PAT }}
